### ISSUE TITLE
default origin documentation

### ISSUE THREAD

**Issue by justin-hackin** [thednp/svg-path-commander#33]
> path command transformations are all consistent with the SVG coordinates system, where others compute transform origin only for rotation transformation.

I found it a bit confusing that the default origin is something other than [0, 0] as in the DOM. That being said, it's not clear where the default origin is in relation to the bounding box given this statement.

**Comment by thednp** [comment]
Since the `transformPath()` utility DOES use the `[0,0,0]` transform origin, it really needs to have it specitied, the SVGPathCommander constructor will compute the shape's center and use it as the origin for its transforms. How all that makes sense, I hope it does, however, for the purpose of the demo and ease of use, I decided it would be best this way.

Now if you want to have a more clear documentation, please let me know what you would change.

**Comment by thednp** [comment]
If you have an idea on how to better explain, please feel free to make a PR.

Closing this down meanwhile.
