### ISSUE TITLE
Feature request: A way to only normalize path command without making coordinates absolute

### ISSUE THREAD

**Issue by farskid** [thednp/svg-path-commander#45]
Thanks for the great library!

I recently ran into a limitation where I need to convert shorthand SVG path commands to standard command. For that, there's the `normalize` method but that also changes all relative coordinates to absolute ones. That was a problem for my specific use-case because the SVG was interactive and there was a dragging event involved. The drag events sent DOM coordinates which were relative to the bounding box of the SVG. Once normalized, absolute coordinates no longer worked with the DOM coordinates being sent. I eventually worked around it by converting DOM events to absolute SVG coordinates based on SVG viewbox but I feel there needs to be a way, preferably a lower level method, to only standardize path commands.

Proposed low level method:
```js
const parsed = new SVGPathCommander(pathData);
const standardPathCommands = parsed.normalizeCommands();
```

**Comment by thednp** [comment]
Out of my head right now I can tell you that absolute values are **always** needed to process segments or else you loose the path shape. For instance a `C` absolute segment followed by an `s` relative segment, how do you normalize in these cases? Either have them both relative or both absolute, but absolute makes more sense because everything else is computed in absolute values: path length, point at length, bbox, etc.

Here's how bbox is computed with [SvgPath](https://github.com/mondeja/svg-path-bbox/blob/master/src/index.ts#L92-L189) for instance:
```ts
  SvgPath.from(d)
    .abs()
    .unarc()
    .unshort()
    .getBBox()
```

In your case:

```ts
const parsed = new SVGPathCommander(pathData);
const standardPathCommands = parsed.normalize().toRelative(); // yes, you can chain methods
```
is actually all you have to do, really. Unless your paths have thousands of segments where this kind of low level implementation would be required, thinking of it I can see how the code might look like, but it wouldn't make sense to add another iterator for this specific case when you can already achieve same result with the existing methods, as shown above.

Cheers :wine_glass:

**Comment by farskid** [comment]
Thanks for the insights, @thednp!
It's interesting to know that absolute coordinates are used internally for all sorts of measurements. I understand the reasoning behind what you explained.

For some reason, using `toRelative` didn't quite work for my case but I didn't dig deep enough to figure it out.

**Comment by thednp** [comment]
You might need to make sure both your expected outcome and your parent function work with the same type of values.
